version: "3.6"
services:
  uwiserApi:
    image: dotnet-criatec-uwiserapi:1.0.0
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3456:80"
    volumes:
      - /home/criatec/images:/data/images
    # depends_on:
    #   - database
    # links:
    #   - database
    # entrypoint: ./wait-for-it.sh database:3306 -s -t 5 -- echo 'INICIALIZANDO'  

  database:
    build: ./mariadb
    image: mariadb
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=teste
      - MYSQL_DATABASE=uwiser
      - MARIADB_EXTRA_FLAGS=--max-connect-errors=1000 --max_connections=10000
#    volumes:
#      - /data/mariadb:/var/lib/mysql/
    command:
      --max-connections=10000 --connect-timeout=10  --query-cache-limit=4M --query-cache-size=64M --expire-logs-days=10  --bulk-insert-buffer-size=16M --tmp-table-size=256M
      --max-heap-table-size=2048M

  # translator:
  #   # container_name: libretranslate
  #   build: ./libre-translator
  #   image: libretranslate/libretranslate
  #   ports:
  #      - "5000:5000"
  #   # build: .
  #   restart: unless-stopped
  # translator:
  #   container_name: libretranslate
  #   build: ./libre-translator
  #   restart: unless-stopped
  #   ports:
  #     - 5000:5000